(() => {
  const card=document.getElementById("successCard");
  addEventListener("DOMContentLoaded",load);
  async function load(){const sessionId=new URLSearchParams(location.search).get("session_id")||"";if(!/^cs_(test_|live_)?[A-Za-z0-9_]+$/.test(sessionId)){showError("ไม่พบหมายเลขรายการชำระเงิน");return}try{let data=await fetchResult(sessionId);if(data.session?.kind==="membership"&&data.session.paymentStatus==="paid"&&!data.session.membership?.active){for(let attempt=0;attempt<4;attempt+=1){await new Promise(resolve=>setTimeout(resolve,1500));data=await fetchResult(sessionId);if(data.session?.membership?.active)break}}render(data.session||{})}catch(error){showError(error?.message||"ตรวจสอบการชำระเงินไม่สำเร็จ")}}
  async function fetchResult(sessionId){const response=await window.TarotPortal.api(`/api/billing/session?session_id=${encodeURIComponent(sessionId)}`,{timeout:20000}),data=await response.json();if(!response.ok)throw window.TarotPortal.apiError(data,"ตรวจสอบการชำระเงินไม่สำเร็จ");return data}
  function render(value){const paid=value.paymentStatus==="paid"||value.paymentStatus==="no_payment_required",support=value.kind==="support";card.setAttribute("aria-busy","false");card.innerHTML=`<div class="success-mark" aria-hidden="true">${paid?"✓":"…"}</div><p class="eyebrow">${support?"THANK YOU FOR YOUR SUPPORT":"TAROT FOR YOUR DAILY"}</p><h1>${paid?(support?"ขอบคุณที่สนับสนุนเรา":"ขอบคุณที่เป็นสมาชิกพิเศษ"):"กำลังยืนยันการชำระเงิน"}</h1><p>${paid?(support?"การสนับสนุนของคุณช่วยให้เราดูแลพื้นที่นี้และสร้างสิ่งใหม่ต่อไป":"เราได้รับการชำระเงินแล้ว สิทธิ์ของคุณกำลังพร้อมใช้งาน"):"การชำระเงินบางประเภทอาจใช้เวลายืนยัน กรุณากลับมาตรวจสอบอีกครั้งในภายหลัง"}</p><div class="billing-summary"><div><span>ยอดชำระ</span><strong>${formatMoney(value.amountTotal,value.currency)}</strong></div><div><span>สถานะ</span><strong>${paid?"ชำระแล้ว":"รอยืนยัน"}</strong></div>${value.membership?.currentPeriodEnd?`<div><span>สิทธิ์ถึงวันที่</span><strong>${formatDate(value.membership.currentPeriodEnd)}</strong></div>`:""}</div><div class="success-actions" id="successActions"></div>`;const actions=document.getElementById("successActions");if(value.receiptUrl){const receipt=document.createElement("a");receipt.href=value.receiptUrl;receipt.target="_blank";receipt.rel="noopener noreferrer";receipt.textContent="ดูใบเสร็จ";actions.append(receipt)}if(value.kind==="membership"){const account=document.createElement("a");account.className="secondary";account.href="../../me/";account.textContent="ไปที่หน้า ฉัน";actions.append(account)}const back=document.createElement("a");back.className="secondary";back.href=value.kind==="membership"?"../../membership/":"../../";back.textContent="กลับไปที่ Tarot";actions.append(back)}
  function showError(message){card.setAttribute("aria-busy","false");card.innerHTML=`<p class="eyebrow">PAYMENT STATUS</p><h1>ยังตรวจสอบไม่ได้</h1><p>${escapeHtml(message)}</p><div class="success-actions"><a class="secondary" href="../../">กลับไปที่ Tarot</a></div>`}
  function formatMoney(amount,currency){if(!Number.isInteger(amount)||!currency)return "—";return new Intl.NumberFormat("th-TH",{style:"currency",currency:currency.toUpperCase()}).format(amount/100)}
  function formatDate(value){try{return new Intl.DateTimeFormat("th-TH",{dateStyle:"long",timeZone:"Asia/Bangkok"}).format(new Date(value))}catch{return value}}
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
})();
