(()=>{
  const API="https://api.sorasukt.com";let catalog=[];
  document.addEventListener("DOMContentLoaded",()=>{
    document.querySelector('[data-view="codes"]')?.addEventListener("click",loadAll);
    document.querySelector('[data-jump="codes"]')?.addEventListener("click",loadAll);
    document.querySelector('[data-refresh="codes"]')?.addEventListener("click",loadAll);
    document.getElementById("codeForm")?.addEventListener("submit",createCode);
    document.getElementById("catalogPrice")?.addEventListener("change",catalogChanged);
  });
  async function loadAll(){await Promise.all([loadCodes(),loadCatalog()])}
  async function loadCatalog(){const select=document.getElementById("catalogPrice");if(!select)return;select.innerHTML='<option value="">กำลังโหลด Stripe Catalog…</option>';try{const data=await api("/api/admin/redeem-codes?source=catalog&limit=100");catalog=data.catalog||[];select.innerHTML='<option value="">เลือกรายการจาก Catalog</option>'+catalog.map(item=>`<option value="${attr(item.priceId)}">${esc(item.productName)} · ${esc(typeLabel(item.paymentType))} · ${money(item.amount,item.currency)}${item.plan?` · ${esc(planLabel(item.plan))}`:""}</option>`).join("");catalogChanged()}catch(e){select.innerHTML='<option value="">โหลด Catalog ไม่สำเร็จ</option>';notice(e.message||"โหลด Stripe Catalog ไม่สำเร็จ",true)}}
  function catalogChanged(){const id=document.getElementById("catalogPrice")?.value,item=catalog.find(x=>x.priceId===id),plan=document.getElementById("catalogPlan"),hint=document.getElementById("catalogHint");if(!plan||!hint)return;if(item?.plan){plan.value="";hint.textContent=`${item.productName} · ${typeLabel(item.paymentType)} · ระบบพบระยะเวลา ${planLabel(item.plan)} จาก Catalog`; }else if(item){hint.textContent=`${item.productName} เป็น ${typeLabel(item.paymentType)} และยังไม่มี plan_period ใน Catalog กรุณาเลือกระยะเวลาสิทธิ์`; }else hint.textContent="สำหรับ One-time price ที่ไม่มี plan_period ใน metadata ให้เลือกระยะเวลาสิทธิ์ด้านบน"}
  async function loadCodes(){const body=document.getElementById("codesBody");if(!body)return;body.innerHTML='<tr><td colspan="7" class="empty">กำลังดึงโค้ดจาก Stripe…</td></tr>';try{const {codes=[]}=await api("/api/admin/redeem-codes?source=stripe&limit=100");body.innerHTML=codes.length?codes.map(row).join(""):'<tr><td colspan="7" class="empty">ยังไม่มี Promotion Code ใน Stripe</td></tr>';body.querySelectorAll("[data-copy-code]").forEach(b=>b.addEventListener("click",()=>copy(b.dataset.copyCode,"คัดลอกโค้ดแล้ว")));body.querySelectorAll("[data-copy-link]").forEach(b=>b.addEventListener("click",()=>copy(b.dataset.copyLink,"คัดลอกลิงก์แล้ว")));body.querySelectorAll("[data-sync-code]").forEach(b=>b.addEventListener("click",()=>syncCode(b)))}catch(e){body.innerHTML=`<tr><td colspan="7" class="empty">${esc(e.message||"ดึงข้อมูลจาก Stripe ไม่สำเร็จ")}</td></tr>`;notice(e.message||"ดึงข้อมูลจาก Stripe ไม่สำเร็จ",true)}}
  async function syncCode(button){const current=button.dataset.plan||"";let plan=current;if(!plan){plan=String(prompt("เลือกระยะเวลาสิทธิ์: weekly, monthly หรือ yearly","yearly")||"").trim().toLowerCase();if(!["weekly","monthly","yearly"].includes(plan)){notice("กรุณาเลือกระยะเวลาสิทธิ์ให้ถูกต้อง",true);return}}button.disabled=true;const old=button.textContent;button.textContent="กำลัง Sync…";try{const {redeem}=await api("/api/admin/redeem-codes",{method:"POST",body:JSON.stringify({source:"stripe_sync",promotionCodeId:button.dataset.syncCode,plan})});notice(redeem.alreadySynced?"โค้ดนี้อยู่ใน Redeem แล้ว":"Sync โค้ดเข้า Redeem แล้ว");if(redeem.redeemUrl)await copy(redeem.redeemUrl,"Sync สำเร็จและคัดลอกลิงก์แล้ว");await loadCodes()}catch(e){notice(e.message||"Sync โค้ดไม่สำเร็จ",true)}finally{button.disabled=false;button.textContent=old}}
  async function createCode(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]'),v=Object.fromEntries(new FormData(form).entries());const payload={source:"stripe",catalogPriceId:v.catalogPriceId,plan:v.plan,code:String(v.code||"").trim(),note:String(v.note||"").trim()};if(v.expiresAt)payload.expiresAt=new Date(v.expiresAt).toISOString();button.disabled=true;button.textContent="กำลังสร้าง…";try{const {redeem}=await api("/api/admin/redeem-codes",{method:"POST",body:JSON.stringify(payload)}),root=document.getElementById("createdCode");root.classList.remove("hidden");root.innerHTML=`<strong>${esc(redeem.code)}</strong><span>${esc(planLabel(redeem.plan))} · ${esc(typeLabel(redeem.paymentType))}</span><div><button type="button" data-created-copy-code>คัดลอกโค้ด</button><button type="button" class="primary" data-created-copy-link>คัดลอกลิงก์</button></div><small>${esc(redeem.redeemUrl)}</small>`;root.querySelector("[data-created-copy-code]").addEventListener("click",()=>copy(redeem.code,"คัดลอกโค้ดแล้ว"));root.querySelector("[data-created-copy-link]").addEventListener("click",()=>copy(redeem.redeemUrl,"คัดลอกลิงก์แล้ว"));form.reset();catalogChanged();notice("สร้าง Redeem Code จาก Stripe Catalog แล้ว");await loadCodes()}catch(e){notice(e.message||"สร้างโค้ดไม่สำเร็จ",true)}finally{button.disabled=false;button.textContent="สร้างใน Stripe"}}
  function row(code){const link=code.redeemUrl||"",sync=code.id&&code.status==="active"&&Number(code.times_redeemed||0)===0?`<button type="button" data-sync-code="${attr(code.id)}" data-plan="${attr(code.plan_period||"")}">Sync เข้า Redeem</button>`:"";const actions=`<div class="code-actions"><button type="button" data-copy-code="${attr(code.code)}">คัดลอกโค้ด</button>${link?`<button type="button" class="primary" data-copy-link="${attr(link)}">คัดลอกลิงก์</button>`:'<span class="muted">ยังไม่ระบุระยะเวลาสิทธิ์</span>'}${sync}</div>`;return `<tr><td><strong class="code-value">${esc(code.code||"-")}</strong>${code.product_name?`<small>${esc(code.product_name)}</small>`:""}</td><td>${esc(planLabel(code.plan_period))}</td><td>${esc(typeLabel(code.payment_type))}</td><td><span class="badge ${esc(code.status||"")}">${esc(code.status||"-")}</span></td><td>${Number(code.times_redeemed||0)}${code.max_redemptions!=null?` / ${Number(code.max_redemptions)}`:""}</td><td>${date(code.expires_at)}</td><td>${actions}</td></tr>`}
  async function api(path,options={}){const response=await fetch(API+path,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let data={};try{data=await response.json()}catch{}if(!response.ok){const e=new Error(data?.error?.message||`Request failed (${response.status})`);e.status=response.status;throw e}return data}
  async function copy(value,message){try{await navigator.clipboard.writeText(value);notice(message)}catch{const a=document.createElement("textarea");a.value=value;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove();notice(message)}}
  function notice(message,error=false){const el=document.getElementById("notice");if(!el)return;el.textContent=message;el.classList.remove("hidden");el.classList.toggle("error",error);setTimeout(()=>el.classList.add("hidden"),4000)}
  function planLabel(v){return ({weekly:"Weekly",monthly:"Monthly",yearly:"Yearly"})[v]||"ไม่ระบุ"}function typeLabel(v){return v==="subscription"?"Subscription":v==="one_time"?"Non-subscription / One-time":v==="redeem"?"Redeem":v||"-"}function money(minor,currency="THB"){try{return new Intl.NumberFormat("th-TH",{style:"currency",currency}).format(Number(minor||0)/100)}catch{return `${Number(minor||0)/100} ${currency}`}}function date(value){if(!value)return"-";const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Bangkok"})}function esc(value){return String(value??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]))}function attr(value){return esc(value).replace(/`/g,"&#96;")}
})();
